#!/bin/bash -e

echo -e "\n\n    RUNNING $(basename $0)\n\n"

# multi media
sudo add-apt-repository ppa:mc3man/bionic-media
sudo apt update

TMPFILE=mktemp
trap "rm -rf $TMPFILE" EXIT
cut -d\# -f1 ../files/packages.common  |grep -v '^$' >$TMPFILE
sudo xargs -a $TMPFILE apt install -y

# dpkg-reconfigure needs to be run after libdvd-pkg is installed
# https://askubuntu.com/questions/1052993/how-to-install-libdvdcss-so-2-library-to-ubuntu-18-04
sudo dpkg-reconfigure libdvd-pkg 
sudo apt install -y ubuntu-restricted-extras
sudo apt upgrade -y

