#!/bin/bash -e


echo 'deb http://linux.dropbox.com/ubuntu xenial main' |sudo tee /etc/apt/sources.list.d/dropbox.list >/dev/null
sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
sudo apt update

sudo apt install -y dropbox

