#!/bin/bash -e

echo -e "\n\n    RUNNING $(basename $0)\n\n"

#
# Adding support for Samsung wifi MFP printer/scanner
# https://www.bchemnet.com/suldr/
#

cd /tmp
wget https://www.bchemnet.com/suldr/pool/debian/extra/su/suldr-keyring_2_all.deb
sudo apt install -y /tmp/suldr-keyring_2_all.deb
sudo bash -c 'echo "deb https://www.bchemnet.com/suldr/ debian extra" > /etc/apt/sources.list.d/suldr-samsung.list'
sudo apt update
sudo apt install -y suld-driver2-1.00.39

