#!/bin/bash -e

if [[ ! -f pcloud ]] ; then
    echo -e '\nDownload pcloud executable from https://www.pcloud.com/download-free-online-cloud-file-storage.html\n'
else
    chmod +rx pcloud
    sudo mkdir -p /usr/local/bin
    sudo mv pcloud /usr/local/bin/.
fi

